services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: go-server
    depends_on:
      - database
      - cache
    volumes:
      - ./server:/app
      - ~/.air:/root/.air
    ports:
      - "8080:8080"
    networks:
      - wordle-network
  database:
    image: postgres:17.4-alpine3.21
    restart: always
    container_name: database
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
  cache:
    image: redis:7.4.3-alpine3.21
    restart: always
    container_name: cache
    volumes:
      - cache_data:/data
    ports:
      - "6379:6379"
    networks:
      - wordle-network
  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: react-client
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules # for ide's autocomplete ability
    ports:
      - "5173:5173"
    networks:
      - wordle-network
volumes:
  db_data:
    driver: local
  cache_data:
    driver: local

networks:
  wordle-network: