global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-server'
    static_configs:
      - targets: ['server:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'pyroscope'
    static_configs:
      - targets: ['pyroscope:4040']