// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID          uuid.UUID
	WordID      int32
	WordLength  int32
	MaxAttempts int32
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Guess struct {
	ID            uuid.UUID
	GameID        uuid.UUID
	Word          string
	AttemptNumber int32
	SessionID     string
	CreatedAt     pgtype.Timestamptz
}

type WordPool struct {
	ID   int32
	Word string
}
